<?php
declare(strict_types=1);
/* Password hash lives outside the web root in /etc/radio-tunkul-admin.php. */
$configFile='/etc/radio-tunkul-admin.php';
if (!is_file($configFile)) { http_response_code(503); exit('El panel aún no está configurado.'); }
$auth=require $configFile;
session_name('radio_tunkul_admin');
session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>true,'httponly'=>true,'samesite'=>'Strict']);
session_start();
function csrf(): string { if(empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(32)); return $_SESSION['csrf']; }
function denied(): void { http_response_code(403); exit('Solicitud no válida.'); }
function h($v): string { return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); }
function load_data($f): array {$x=json_decode((string)@file_get_contents($f),true);return is_array($x)?$x:['podcasts'=>[],'sources'=>[]];}
function save_data($f,$d): void {$tmp=$f.'.tmp';file_put_contents($tmp,json_encode($d,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);rename($tmp,$f);}
function slug($s): string {$s=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$s);$s=preg_replace('/[^a-zA-Z0-9]+/','-',strtolower((string)$s));return trim($s,'-')?:'audio';}
function public_https_url(string $url): bool { $p=parse_url($url); if(($p['scheme']??'')!=='https'||empty($p['host'])||isset($p['user']))return false; $ips=gethostbynamel($p['host'])?:[]; if(!$ips)return false; foreach($ips as $ip)if(!filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE))return false; return true; }
if (isset($_GET['logout'])) { $_SESSION=[]; session_destroy(); header('Location: /radio-admin/'); exit; }
if (empty($_SESSION['radio_admin'])) {
  $error=''; if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='login') { if(!hash_equals(csrf(),(string)($_POST['csrf']??'')))denied(); if(password_verify((string)($_POST['password']??''),(string)($auth['password_hash']??''))){session_regenerate_id(true);$_SESSION['radio_admin']=true;header('Location: /radio-admin/');exit;} $error='Contraseña incorrecta.'; }
  ?><!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Radio Tunkul · Acceso</title><style>body{margin:0;background:#eee1ca;color:#2a2018;font:15px system-ui}main{max-width:400px;margin:12vh auto;padding:25px;background:#fff8ec;border:1px solid #d6c29e;border-radius:12px}h1{font-family:Georgia,serif}input{width:100%;box-sizing:border-box;padding:11px;border:1px solid #cbb38d;border-radius:7px}button{margin-top:14px;padding:11px 16px;background:#28342c;color:#fff;border:0;border-radius:7px;font-weight:700}.err{color:#9a241c}</style><main><h1>Radio Tunkul</h1><p>Administración privada</p><?php if($error):?><p class="err"><?=h($error)?></p><?php endif;?><form method="post"><input type="hidden" name="action" value="login"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><label>Contraseña</label><input required autofocus type="password" name="password" autocomplete="current-password"><button>Entrar</button></form></main></html><?php exit;
}
$base=dirname(__DIR__);$dataFile=$base.'/data/content.json';$mediaDir=$base.'/media';if(!is_dir($mediaDir))mkdir($mediaDir,0755,true);$data=load_data($dataFile);$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals(csrf(),(string)($_POST['csrf']??'')))denied();
  if(($_POST['action']??'')==='source'){ $name=trim($_POST['name']??'');$url=trim($_POST['url']??'');if($name&&public_https_url($url)){$data['sources'][]=['name'=>$name,'url'=>$url];save_data($dataFile,$data);$notice='Fuente agregada.';}else $error='Usa una URL RSS pública con HTTPS.'; }
  if(($_POST['action']??'')==='podcast'){ $title=trim($_POST['title']??'');$category=trim($_POST['category']??'General');$desc=trim($_POST['description']??'');$f=$_FILES['audio']??null;$ok=$f&&$f['error']===UPLOAD_ERR_OK&&$f['size']<=104857600;if(!$title||!$ok)$error='Título y audio (máximo 100 MB) son obligatorios.';else{$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$ext=['audio/mpeg'=>'mp3','audio/mp4'=>'m4a','audio/x-m4a'=>'m4a','audio/wav'=>'wav'][$mime]??null;if(!$ext)$error='Formato permitido: MP3, M4A o WAV.';else{$file=date('Ymd').'-'.bin2hex(random_bytes(4)).'-'.slug($title).'.'.$ext;if(!move_uploaded_file($f['tmp_name'],$mediaDir.'/'.$file))$error='No se pudo guardar el audio.';else{$data['podcasts'][]=['id'=>bin2hex(random_bytes(8)),'title'=>$title,'category'=>$category,'description'=>$desc,'date'=>date('Y-m-d'),'audio'=>'/radio/media/'.$file,'published'=>true];save_data($dataFile,$data);$notice='Podcast publicado.';}}}
  }
}
?><!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Radio Tunkul · Administración</title><style>body{margin:0;background:#eee1ca;color:#2a2018;font:15px system-ui}main{max-width:900px;margin:35px auto;padding:0 18px}h1,h2{font-family:Georgia,serif}.card{background:#fff8ec;border:1px solid #d6c29e;border-radius:12px;padding:20px;margin:16px 0}label{display:block;margin:12px 0 5px;font-weight:700}input,textarea{width:100%;padding:10px;border:1px solid #cbb38d;border-radius:7px;font:inherit}button{margin-top:15px;background:#28342c;color:#fff7e8;border:0;border-radius:7px;padding:11px 16px;font-weight:700}.ok{color:#176b38}.error{color:#9a241c}.item{padding:10px 0;border-top:1px solid #e5d4b9}.small{color:#6c6254;font-size:13px}.right{float:right}</style><main><p><a href="/radio">← Ver Radio Tunkul</a><a class="right" href="?logout=1">Cerrar sesión</a></p><h1>Administración de Radio Tunkul</h1><?php if($notice):?><p class="ok"><?=h($notice)?></p><?php endif;?><?php if($error):?><p class="error"><?=h($error)?></p><?php endif;?><section class="card"><h2>Publicar podcast</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="podcast"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><label>Título</label><input required name="title" maxlength="140"><label>Categoría</label><input name="category" value="Historias de Tunkul" maxlength="80"><label>Descripción</label><textarea name="description" rows="3" maxlength="1000"></textarea><label>Audio (MP3, M4A o WAV; máximo 100 MB)</label><input required name="audio" type="file" accept="audio/mpeg,audio/mp4,audio/x-m4a,audio/wav"><button>Publicar podcast</button></form></section><section class="card"><h2>Fuentes RSS</h2><p class="small">Sólo se aceptan URLs HTTPS públicas. La portada muestra título, fecha, fuente y enlace original.</p><form method="post"><input type="hidden" name="action" value="source"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><label>Nombre de la fuente</label><input required name="name" maxlength="100" placeholder="Ej. RFI en Español"><label>URL del RSS</label><input required type="url" name="url" placeholder="https://…"><button>Agregar fuente</button></form><?php foreach($data['sources'] as $s):?><div class="item"><strong><?=h($s['name'])?></strong><br><span class="small"><?=h($s['url'])?></span></div><?php endforeach;?></section><section class="card"><h2>Biblioteca</h2><?php foreach(array_reverse($data['podcasts']) as $p):?><div class="item"><strong><?=h($p['title'])?></strong> · <?=h($p['category']??'')?><br><span class="small"><?=h($p['date']??'')?></span></div><?php endforeach;?><?php if(empty($data['podcasts'])):?><p class="small">Aún no hay podcasts publicados.</p><?php endif;?></section></main></html>
